version: 2
updates:
  - package-ecosystem: npm
    directory: /Client
    schedule:
      interval: weekly
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: nuget
    directory: /Server
    schedule:
      interval: weekly
    groups:
      nuget-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
