name: Server

on:
  push:
    branches:
      - main
    paths:
      - 'Server/**'
      - 'global.json'
      - '.editorconfig'
      - '.github/workflows/Server.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'Server/**'
      - 'global.json'
      - '.editorconfig'
      - '.github/workflows/Server.yml'

jobs:
  build:
    if: github.event_name == 'push' || github.event.action != 'closed'
    runs-on: windows-latest
    name: Build
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v7

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: '**/appsettings.json'
        env:
          ApplicationSettings.AzureBlobStorage.ConnectionString: ${{ secrets.AS_ABS_CONNECTION_STRING }}
          ApplicationSettings.AzureBlobStorage.ContainerName: ${{ secrets.AS_ABS_CONTAINER_NAME }}
          ApplicationSettings.AzureBlobStorage.ProfilePictureBlobName: ${{ secrets.AS_ABS_PROFILE_PICTURE_BLOB_NAME }}
          ApplicationSettings.AzureBlobStorage.ResumeBlobName: ${{ secrets.AS_ABS_RESUME_BLOB_NAME }}

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.x'

      - name: Build with dotnet
        run: dotnet build Server --configuration Release

      - name: Verify formatting
        run: dotnet format Server --verify-no-changes --no-restore

      - name: dotnet publish
        run: dotnet publish Server -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    if: github.event_name == 'push'
    runs-on: windows-latest
    needs: build
    name: Deploy
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v8
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D2A6075AF1BD4C16B637CF66E656DE25 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A186845659974C2EB3373F11AB0FDDDC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A1E2FC05DE4F435691EDCF752F019B66 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BHSBackend'
          slot-name: 'Production'
          package: .
